# Generated by Django 5.2.1 on 2026-05-28 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="auditevent",
            index=models.Index(
                fields=["tenant", "created_at"], name="core_audite_tenant__b7d570_idx"
            ),
        ),
    ]
